### ISSUE TITLE
History of transfers per league on admin transfers page

### ISSUE THREAD

**Issue by obla** [ozfortress/citadel#227] opened 2017-05-02 08:09 UTC

**Comment by BenjaminSchaaf** [comment] 2017-05-13 13:26
How do we want this to work? Show all transfers for everyone requesting a transfer?

**Comment by obla** [comment] 2017-05-13 13:29
Or 'obla' accepted X's transfer from 1 to 2 on DATE.

**Comment by BenjaminSchaaf** [comment] 2017-05-13 13:30
We don't track who accepted the transfer right now, do we want to do that?

**Comment by BenjaminSchaaf** [comment] 2017-05-13 13:31
None the less I don't see how your suggestion is any different to mine?

**Comment by obla** [comment] 2017-05-13 13:31
Would be nice if it's not too much work.

**Comment by obla** [comment] 2017-05-13 13:32
Well then yes history of all requested transfers for that league. The 'or' in my comment is redundant.

**Comment by BenjaminSchaaf** [comment] 2017-05-13 13:36
*All* previously requested transfers, including denied ones? That'll be a very cluttered page.

**Comment by obla** [comment] 2017-05-13 13:37
Definitely denied ones. Some people ask why was my transfer denied and I want to be able to track that. I don't know how to declutter. By week?

**Comment by BenjaminSchaaf** [comment] 2017-05-13 13:39
'Week' isn't really a solid concept.

**Comment by obla** [comment] 2017-05-13 13:47
I'm ok sorting with time; any other suggestions?

**Comment by BenjaminSchaaf** [comment] 2017-05-13 13:55
Can't think of any

**Comment by BenjaminSchaaf** [comment] 2017-05-20 10:00
Duplicate of #213

**Closed by BenjaminSchaaf** 2017-05-20 10:00 UTC
Labels: PRIORITY
